# Generated by Django 4.2.11 on 2024-04-13 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ranked_choice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservote',
            name='ip_address',
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vote',
            name='vote_candidates',
            field=models.ManyToManyField(to='ranked_choice.candidate'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='image',
            field=models.ImageField(upload_to='candidates'),
        ),
        migrations.AlterField(
            model_name='uservote',
            name='user_candidates',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uservote',
            name='vote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_votes', to='ranked_choice.vote'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='results',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='uservote',
            index=models.Index(fields=['ip_address', 'vote'], name='ranked_choi_ip_addr_7419b3_idx'),
        ),
    ]
